services:
  parsedmarc:
    build: ./parsedmarc/
    networks:
      - dmarc_net
    environment:
      - no_proxy=elasticsearch,localhost,127.0.0.1,grafana
      - NO_PROXY=elasticsearch,localhost,127.0.0.1,grafana
      - http_proxy=http://proxy:port
      - https_proxy=http://proxy:port
    volumes:
      - ./input_files:/input:rw
      - ./output_files:/output:rw
      - ./parsedmarc/parsedmarc.ini:/etc/parsedmarc.ini
      - ./run_parsedmarc.sh:/run_parsedmarc.sh:ro
    command: /bin/sh /run_parsedmarc.sh
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.5
    networks:
      - dmarc_net
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    networks:
      - dmarc_net
    ports:
      - "3000:3000"
    user: root
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - elasticsearch

networks:
  dmarc_net:
    driver: bridge

volumes:
  elastic_data:
  grafana_data:
