apiVersion: 1

datasources:
  - name: elasticsearch
    type: elasticsearch
    access: proxy
    isDefault: true
    url: http://elasticsearch:9200
    database: parsedmarc*
    uid: parsedmarc-es
    jsonData:
      esVersion: 8
      timeField: date_begin
      interval: "Daily"
    secureJsonData: {}
    version: 1
    editable: false
