[general]
save_aggregate = True
save_forensic = True
offline = True

[elasticsearch]
hosts = http://elasticsearch:9200
ssl = False
index_prefix = dmarc-
use_daily = False

[logging]
# DEBUG から INFO に変更（正常終了したファイル名などの重要な情報のみ出力）
#level = DEBUG
level = INFO
